# Documentation: https://www.navidrome.org/docs/usage/docker/
services:
  navidrome:
    image: deluan/navidrome:latest
    user: 1000:1000 # should be owner of volumes
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      # Optional: put your config options customization here. Examples:
      # ND_LOGLEVEL: debug
    volumes:
      - "/path/to/data:/data"
      - "/path/to/your/music/folder:/music:ro"


# Optional: Define a persistent named volume for data instead of bind mount
# volumes:
#   navidrome_data: