# .github/workflows/ci.yml
# https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners
# https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/running-variations-of-jobs-in-a-workflow

name: togeprii CI

on:
    push:
        branches:
            - main
            - 'feature/**'
    pull_request:
        branches:
            - main

jobs:
    lint:
        name: ShellCheck Linting
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install ShellCheck
              run: |
                  sudo apt-get update
                  sudo apt-get install -y shellcheck

            - name: Run ShellCheck (fail only on errors)
              run: shellcheck --severity=error -x *.sh helpers.sh tests/*.sh

    test-installations:
        name: Test Installation (Stage ${{ matrix.stage }})
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                stage:
                    - "--system"
                    - "--apps"
                    - "--dev"
                    # - "--all" TODO: Add --all flag once the project is almost done

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Prepare Test Environment
              run: |
                  sudo apt-get update
                  sudo apt-get install -y lsb-release python3-pip flatpak virt-manager
                  sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

            - name: Run togeprii installation test for stage ${{ matrix.stage }}
              run: |
                chmod +x ./tests/run_installation_test.sh 
                ./tests/run_installation_test.sh "${{ matrix.stage }}"

            - name: Check installed Docker version (if dev stage was run)
              if: success() && (matrix.stage == '--dev' || matrix.stage == '--all')
              run: docker --version

            - name: Check installed Flatpak apps (if apps stage was run)
              if: success() && (matrix.stage == '--apps' || matrix.stage == '--all')
              run: flatpak list

# Matrix will be in charge of running the --system, --apps, --dev flags
# as separate test runs. --all might run too slow for now, but will eventually
# get added. 



# TODO(?): It could be possible to make these tests run on a Fedora container
# inside the Ubuntu runner. Running a DinD, checking if it can run hello-world
# and trying to get a Fedora docker image inside the Ubuntu runner, but might be
# too complicated luls. 